In [21]:
import pandas as pd
dobs = pd.DataFrame({'name': ['Suzy', 'Wei','Yulia', 'Arvind'],
                   'day': ['12', '19', '2', '23'],
                   'month': ['Dec', 'Nov', 'May', 'Jul']})

addresses = pd.DataFrame({'name': ['Marisol', 'Arvind','Stephan', 'Suzy'],
                     'city': ['San Francisco', 'Denver', 'Austin', 'Seattle'],
                     'state': ['CA', 'CO', 'TX', 'WA']})


birthday_address = [dobs, addresses]
birthday_address2 = pd.concat(birthday_address, axis=0)

/home/cowbatcat/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if sys.path[0] == '':


In [22]:
birthday_address2

city  day month     name state
0            NaN   12   Dec     Suzy   NaN
1            NaN   19   Nov      Wei   NaN
2            NaN    2   May    Yulia   NaN
3            NaN   23   Jul   Arvind   NaN
0  San Francisco  NaN   NaN  Marisol    CA
1         Denver  NaN   NaN   Arvind    CO
2         Austin  NaN   NaN  Stephan    TX
3        Seattle  NaN   NaN     Suzy    WA

In [24]:
import numpy as np

In [25]:
grocery = pd.DataFrame({'category':['produce', 'produce', 'meat',
                                        'meat', 'meat', 'cheese', 'cheese'],
                            'item':['celery', 'apple', 'ham', 'turkey',
                                    'lamb', 'cheddar', 'brie'],
                            'price':[.99, .49, 1.89, 4.34, 9.50, 6.25, 8.0]})

In [27]:
grocery.groupby('category')

In [28]:
grouped = grocery.groupby('category')
grouped.aggregate(np.mean)

# Category becomes the index of the above output

price
category          
cheese    7.125000
meat      5.243333
produce   0.740000

In [29]:
grouped.transform(lambda x: x - x.mean())

# Notice index is the same as original grocery data.

price
0  0.250000
1 -0.250000
2 -3.353333
3 -0.903333
4  4.256667
5 -0.875000
6  0.875000

In [30]:
grouped.filter(lambda x: len(x)>2)

# Notice index is a subset of original data.

category    item  price
2     meat     ham   1.89
3     meat  turkey   4.34
4     meat    lamb   9.50

In [32]:
import pandas as pd
import numpy as np

grocery = pd.DataFrame({'category':['produce', 'produce', 'meat',
                                    'meat', 'meat', 'cheese', 'cheese'],
                        'item':['celery', 'apple', 'ham', 'turkey',  'lamb',
                                'cheddar', 'brie'],
                        'price':[.99, .49, 1.89, 4.34, 9.50, 6.25, 8.0]})

grouped = grocery.groupby('category')
grouped.filter(lambda x: np.mean(x)>=3)

category     item  price
2     meat      ham   1.89
3     meat   turkey   4.34
4     meat     lamb   9.50
5   cheese  cheddar   6.25
6   cheese     brie   8.00

In [34]:
grouped.aggregate(np.max)

item  price
category                
cheese    cheddar   8.00
meat       turkey   9.50
produce    celery   0.99

In [40]:
grouped_price = grocery.groupby('category')['price']

In [43]:
grouped_price.transform(lambda x: x*.9 if np.max(x)>3 else x)

0    0.990
1    0.490
2    1.701
3    3.906
4    8.550
5    5.625
6    7.200
Name: price, dtype: float64

In [45]:
grouped.transform(lambda x: x*.9 if np.max(x)>3 else x)

price
0  0.990
1  0.490
2  1.701
3  3.906
4  8.550
5  5.625
6  7.200

A common task faced by data scientists involves identifying a company's most valuable customers. This usually involves aggregating each customer's purchase history.

Assume that you are working with two DataFrames: `customers`, and `orders`. The `customers` DataFrame contains a unique `customer_id` for each customer and other relevant info like name and email address. `orders` contains an `order_id`, the `customer_id` of the person who placed the order, and the the `order_total` in dollars.

Fill in the Pandas code below to create a new DataFrame, `customer_spend`, that contains the following columns in this order: `customer_id`, `name`, and `total_spend`. `total_spend` is a new column containing the sum of the cost of all the orders that a particular customer placed. Note that this is likely to take a few steps!

Hint: The column you groupby is not included as a column in the output DataFrame, but as its index. If you then try to merge on that column (which isn't there), Pandas looks for it and can't find it. A handy way to get around this type of problem is the .reset_index() method, which was mentioned towards the end of Pandas Lesson 4 on split-apply-combine.


In [94]:
import pandas as pd
import numpy as np

customers = pd.DataFrame([[100, 'Prometheus Barwis', 'prometheus.barwis@me.com',
        '(533) 072-2779'],[101, 'Alain Hennesey', 'alain.hennesey@facebook.com',
        '(942) 208-8460'],[102, 'Chao Peachy', 'chao.peachy@me.com',
        '(510) 121-0098'],[103, 'Somtochukwu Mouritsen',
        'somtochukwu.mouritsen@me.com','(669) 504-8080'],[104,
        'Elisabeth Berry', 'elisabeth.berry@facebook.com','(802) 973-8267']],
        columns = ['customer_id', 'name', 'email', 'phone'])

orders = pd.DataFrame([[1000, 100, 144.82], [1001, 100, 140.93],
       [1002, 102, 104.26], [1003, 100, 194.6 ], [1004, 100, 307.72],
       [1005, 101,  36.69], [1006, 104,  39.59], [1007, 104, 430.94],
       [1008, 103,  31.4 ], [1009, 104, 180.69], [1010, 102, 383.35],
       [1011, 101, 256.2 ], [1012, 103, 930.56], [1013, 100, 423.77],
       [1014, 101, 309.53], [1015, 102, 299.19]],
       columns = ['order_id', 'customer_id', 'order_total'])

# Combine and aggregate the above DataFrames according to the instructions.
# Feel free to use multiple steps.

customers_orders = pd.merge(customers, orders, on='customer_id', how='outer')
grouped_customers_orders = customers_orders.groupby('customer_id')
name = grouped_customers_orders['name'].aggregate(pd.Series.mode)
total_spend = grouped_customers_orders['order_total'].aggregate(np.sum)

# Learn will check the contents/column names of the customer_spend object.
customer_spend_index = pd.DataFrame({'name': name, 'total_spend': total_spend})
customer_spend = customer_spend_index.reset_index()
customer_spend

customer_id                   name  total_spend
0          100      Prometheus Barwis      1211.84
1          101         Alain Hennesey       602.42
2          102            Chao Peachy       786.80
3          103  Somtochukwu Mouritsen       961.96
4          104        Elisabeth Berry       651.22

In [54]:
customers_orders = pd.merge(customers, orders, on='customer_id', how='outer')
customers_orders

customer_id                   name                         email  \
0           100      Prometheus Barwis      prometheus.barwis@me.com   
1           100      Prometheus Barwis      prometheus.barwis@me.com   
2           100      Prometheus Barwis      prometheus.barwis@me.com   
3           100      Prometheus Barwis      prometheus.barwis@me.com   
4           100      Prometheus Barwis      prometheus.barwis@me.com   
5           101         Alain Hennesey   alain.hennesey@facebook.com   
6           101         Alain Hennesey   alain.hennesey@facebook.com   
7           101         Alain Hennesey   alain.hennesey@facebook.com   
8           102            Chao Peachy            chao.peachy@me.com   
9           102            Chao Peachy            chao.peachy@me.com   
10          102            Chao Peachy            chao.peachy@me.com   
11          103  Somtochukwu Mouritsen  somtochukwu.mouritsen@me.com   
12          103  Somtochukwu Mouritsen  somtochukwu.mouritsen@me.com   
13          104        Elisabeth Berry  elisabeth.berry@facebook.com   
14          104        Elisabeth Berry  elisabeth.berry@facebook.com   
15          104        Elisabeth Berry  elisabeth.berry@facebook.com   

             phone  order_id  order_total  
0   (533) 072-2779      1000       144.82  
1   (533) 072-2779      1001       140.93  
2   (533) 072-2779      1003       194.60  
3   (533) 072-2779      1004       307.72  
4   (533) 072-2779      1013       423.77  
5   (942) 208-8460      1005        36.69  
6   (942) 208-8460      1011       256.20  
7   (942) 208-8460      1014       309.53  
8   (510) 121-0098      1002       104.26  
9   (510) 121-0098      1010       383.35  
10  (510) 121-0098      1015       299.19  
11  (669) 504-8080      1008        31.40  
12  (669) 504-8080      1012       930.56  
13  (802) 973-8267      1006        39.59  
14  (802) 973-8267      1007       430.94  
15  (802) 973-8267      1009       180.69

In [55]:
grouped_customers_orders = customers_orders.groupby('customer_id')
grouped_customers_orders

In [74]:
total_spend = grouped_customers_orders['order_total'].aggregate(np.sum)
total_spend

customer_id
100    1211.84
101     602.42
102     786.80
103     961.96
104     651.22
Name: order_total, dtype: float64

In [61]:
customers_orders['order_total'].sum()

4214.24

In [89]:
name = grouped_customers_orders['name'].aggregate(pd.Series.mode)
name

customer_id
100        Prometheus Barwis
101           Alain Hennesey
102              Chao Peachy
103    Somtochukwu Mouritsen
104          Elisabeth Berry
Name: name, dtype: object

In [95]:
name = grouped_customers_orders['name'].aggregate(pd.Series.mode)
name

customer_id
100        Prometheus Barwis
101           Alain Hennesey
102              Chao Peachy
103    Somtochukwu Mouritsen
104          Elisabeth Berry
Name: name, dtype: object

In [83]:
customer_spend = pd.DataFrame({'name': grouped_customers_orders['name'].aggregate(pd.Series.mode), 
                               'total_spend': grouped_customers_orders['order_total'].aggregate(np.sum)}).reset_index()

In [90]:
customer_spend = pd.DataFrame({'name': name, 'total_spend': total_spend}).reset_index()

In [91]:
customer_spend

customer_id                   name  total_spend
0          100      Prometheus Barwis      1211.84
1          101         Alain Hennesey       602.42
2          102            Chao Peachy       786.80
3          103  Somtochukwu Mouritsen       961.96
4          104        Elisabeth Berry       651.22

In [ ]:
df["responseCount"] = (df.groupby("item")["response"]
                        .transform(lambda x: x.value_counts().index[0]))

print (df)
   item response responseCount
0     1        A             A
1     1        A             A
2     1        B             A
3     2        C             C
4     2        C             C

In [97]:
name = grouped_customers_orders['name'].aggregate(lambda x: x.value_counts().index[0])
name

customer_id
100        Prometheus Barwis
101           Alain Hennesey
102              Chao Peachy
103    Somtochukwu Mouritsen
104          Elisabeth Berry
Name: name, dtype: object

In [99]:
import pandas as pd
import numpy as np

customers = pd.DataFrame([[100, 'Prometheus Barwis', 'prometheus.barwis@me.com',
        '(533) 072-2779'],[101, 'Alain Hennesey', 'alain.hennesey@facebook.com',
        '(942) 208-8460'],[102, 'Chao Peachy', 'chao.peachy@me.com',
        '(510) 121-0098'],[103, 'Somtochukwu Mouritsen',
        'somtochukwu.mouritsen@me.com','(669) 504-8080'],[104,
        'Elisabeth Berry', 'elisabeth.berry@facebook.com','(802) 973-8267']],
        columns = ['customer_id', 'name', 'email', 'phone'])

orders = pd.DataFrame([[1000, 100, 144.82], [1001, 100, 140.93],
       [1002, 102, 104.26], [1003, 100, 194.6 ], [1004, 100, 307.72],
       [1005, 101,  36.69], [1006, 104,  39.59], [1007, 104, 430.94],
       [1008, 103,  31.4 ], [1009, 104, 180.69], [1010, 102, 383.35],
       [1011, 101, 256.2 ], [1012, 103, 930.56], [1013, 100, 423.77],
       [1014, 101, 309.53], [1015, 102, 299.19]],
       columns = ['order_id', 'customer_id', 'order_total'])

# Combine and aggregate the above DataFrames according to the instructions.
# Feel free to use multiple steps.

customers_orders = pd.merge(customers, orders, on='customer_id', how='outer')
grouped_customers_orders = customers_orders.groupby('customer_id')
name = grouped_customers_orders['name'].aggregate(lambda x: x.value_counts().index[0])
total_spend = grouped_customers_orders['order_total'].aggregate(np.sum)

# Learn will check the contents/column names of the customer_spend object.
customer_spend = pd.DataFrame({'name': name, 'total_spend': total_spend}).reset_index()


Pandas is very useful for performing exploratory data analysis (EDA). One important component of EDA is visualization, so Pandas Series and DataFrame objects include some methods for plotting.

Fill in the function below, according to its docstring, to return a Pandas object for plotting a histogram. (The histogram won't actually be displayed.) Note, we are not asking you to do all the work necessary to make a histogram yourself. Rather, we want to see you leverage Pandas' ability to make histograms easily--the answer may be shorter than you think!


In [ ]:
def df_histogram(df, colname, num_bins = 10):
  """
  Given a Pandas DataFrame, df, return a histogram plotting object for the
  data in the column, specified by colname. Optionally specify the number
  of bins in the histogram with num_bins.

  Parameters
  ----------
  df: (Pandas DataFrame).
  colname: (str) name of column in df to be plotted.
  num_bins: (int) number of bins to include in the histogram plot.

  Returns
  -------
  (Pandas/Matplotlib plot object)
  """

    return df['colname'].plot(type=hist)

In [100]:
type(NaN)

NameError: name 'NaN' is not defined

In [206]:
df = pd.DataFrame({'a':[0,10,None,30], 'b':[None,100,1000,10000], 'c':[1,2,3,4]})


In [207]:
import pandas as pd

def replace_missing(df, replace_method = 'mean'):
    """
    Given a DataFrame, df, any fields that are null (represented in Pandas
    with NaN) will be replaced using the method specified in replace_method.

    Parameters
    ----------
    df: (Pandas DataFrame).

    replace_method: (variable type) 'mean', 'median', 0, -1, 9999999, etc.
        If 'mean'/'median': replace each missing value with the mean/median
                            value of its column.
        If other: any other value will be taken to be a replacement *value*
                  and inserted for the missing values.

    Returns
    -------
    df: (Pandas DataFrame)
    """
    df_nan = df.copy()
    for column in df_nan:
        df_nan[column] = pd.to_numeric(df_nan[column], errors = 'coerce')
    if (replace_method == 'mean' or replace_method == 'median'):
        values = {}
        if replace_method == 'mean':
            for column in df_nan:
                values[column] = df_nan[column].mean()
        else:
            for column in df_nan:
                values[column] = df_nan[column].median()
        df_nan = df_nan.fillna(value=values, inplace=True)
        return df_nan
    else:
        df_nan.fillna(replace_method, inplace=True)
    return df_nan

In [217]:
df = pd.DataFrame({'a':[0,10,None,30], 'b':[None,100,1000,10000], 'c':[1,2,3,4]})

In [228]:
import pandas as pd

def replace_missing(df, replace_method = 'mean'):
    """
    Given a DataFrame, df, any fields that are null (represented in Pandas
    with NaN) will be replaced using the method specified in replace_method.

    Parameters
    ----------
    df: (Pandas DataFrame).

    replace_method: (variable type) 'mean', 'median', 0, -1, 9999999, etc.
        If 'mean'/'median': replace each missing value with the mean/median
                            value of its column.
        If other: any other value will be taken to be a replacement *value*
                  and inserted for the missing values.

    Returns
    -------
    df: (Pandas DataFrame)
    """
    df_nan = df.copy()
    for column in df_nan:
        df_nan[column] = pd.to_numeric(df_nan[column], errors = 'coerce')
    if (replace_method == 'mean' or replace_method == 'median'):
#        values = {}
        if replace_method == 'mean':
            values = {ke: va for (k, v) in df_nan}
#            for column in df_nan:
#                values[column] = df_nan[column].mean()
#            {key: value for (k, v) in df_nan}
        else:
            for column in df_nan:
                values[column] = df_nan[column].median()
        df_nan = df_nan.fillna(value=values, inplace=True)
        return df_nan
    else:
        df_nan.fillna(replace_method, inplace=True)
    return df_nan

In [230]:
df = pd.DataFrame({'a':[0,10,None,30], 'b':[None,100,1000,10000], 'c':[1,2,3,4]})

In [235]:
import pandas as pd

def replace_missing(df, replace_method = 'mean'):
    """
    Given a DataFrame, df, any fields that are null (represented in Pandas
    with NaN) will be replaced using the method specified in replace_method.

    Parameters
    ----------
    df: (Pandas DataFrame).

    replace_method: (variable type) 'mean', 'median', 0, -1, 9999999, etc.
        If 'mean'/'median': replace each missing value with the mean/median
                            value of its column.
        If other: any other value will be taken to be a replacement *value*
                  and inserted for the missing values.

    Returns
    -------
    df: (Pandas DataFrame)
    """
    df_nan = df.copy()
    for column in df_nan:
        df_nan[column] = pd.to_numeric(df_nan[column], errors = 'coerce')
    if (replace_method == 'mean' or replace_method == 'median'):
        if replace_method == 'mean':
            df_nan.fillna(df_nan.mean(), inplace=True)
        else:
            df_nan.fillna(df_nan.median(), inplace=True)
        return df_nan
    else:
        df_nan.fillna(replace_method, inplace=True)
    return df_nan

In [236]:
replace_missing(df)

a        b  c
0   0.000000   3700.0  1
1  10.000000    100.0  2
2  13.333333   1000.0  3
3  30.000000  10000.0  4

In [237]:
replace_missing(df, replace_method = 'median')

a        b  c
0   0.0   1000.0  1
1  10.0    100.0  2
2  10.0   1000.0  3
3  30.0  10000.0  4

In [238]:
replace_missing(df, replace_method = -999)

a        b  c
0    0.0   -999.0  1
1   10.0    100.0  2
2 -999.0   1000.0  3
3   30.0  10000.0  4

In [239]:
df = pd.DataFrame({'a':[0,10,None,30], 'b':[None,100,1000,10000], 'c':[1,2,3,4]})
df

a        b  c
0   0.0      NaN  1
1  10.0    100.0  2
2   NaN   1000.0  3
3  30.0  10000.0  4

In [240]:
np.log(10)

2.302585092994046

In [241]:
np.log(2)

0.6931471805599453

In [242]:
np.log(10)-np.log(2)

1.6094379124341005

In [243]:
import numpy as np

In [244]:
A = np.array([[ 8,  1, -7], [-2, -8,  5], [-5, -5, -8]])
b = np.array([[-71], [ 25], [-51]])

In [247]:
Ainv = np.linalg.inv(A)

In [248]:
Ainv * A

array([[ 0.80817253,  0.04880817,  0.40522134],
       [ 0.09307605,  0.89897843, -0.14755959],
       [ 0.17026107, -0.19863791,  0.56299659]])

In [249]:
np.matmul(A, Ainv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [250]:
np.matmul(Ainv, A)

array([[ 1.00000000e+00, -1.11022302e-16,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00, -1.38777878e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [251]:
np.matmul(Ainv, b)

array([[-3.],
       [ 2.],
       [ 7.]])

In [252]:
(2**.5) * (16.25**.5)

5.70087712549569

In [259]:
B = np.array([[ -5,  3, -1], [-3, 6,  -1], [-1, -7, 3]])
c = np.array([[-10], [18], [-38]])


In [254]:

def format_matrix_string(mat):
    """
    Convert a NumPy matrix/array to a string where rows are separated by the
    newline character '\n'.
    INPUT: mat: NumPy array
    OUTPUT: str
    """
    rowstrs = [', '.join(row) for row in np.round(mat, 2).astype(str)]
    return ' \n '.join(rowstrs)

In [255]:
format_matrix_string(B)

'-5, 3, -1 \n -3, 6, -1 \n -1, -7, 3'

In [256]:
Binv = np.linalg.inv(B)
Binv

array([[-0.21153846,  0.03846154, -0.05769231],
       [-0.19230769,  0.30769231,  0.03846154],
       [-0.51923077,  0.73076923,  0.40384615]])

In [257]:
format_matrix_string(Binv)


'-0.21, 0.04, -0.06 \n -0.19, 0.31, 0.04 \n -0.52, 0.73, 0.4'

In [260]:
Binv.dot(c)

array([[5.],
       [6.],
       [3.]])

In [261]:
np.matmul(Binv, c)

array([[5.],
       [6.],
       [3.]])

In [262]:
P = np.array([8, -3, 8, 5, -5])
Q = np.array([-4, 8, 7, -1, 6])
distance = np.linalg.norm(P - Q)
distance

20.566963801203133

p=[8−385−5]
q=[−487−16]

In [263]:
p=(64+9+64+50)**.5
p

13.674794331177344

In [264]:
q=(16+64+49+1+36)**.5
q

12.884098726725126

In [266]:
a=p*q
a

176.18740023055

In [272]:
dot = ((-32)+(-24)+56+(-5)+(-30))
dot

-35

In [273]:
dot/a

-0.19865211674728586

In [269]:
np.linalg.norm(P)*np.linalg.norm(Q)

176.18740023055

In [270]:
P.dot(Q)

-35

In [271]:
Q.dot(P)

-35

In [274]:
P.dot(Q)/(np.linalg.norm(P)*np.linalg.norm(Q))

-0.19865211674728586

In [276]:
v = np.array([[-2], [0], [1]])
a = np.array([[5, 8, 16], [4, 1, 8], [-4, -4, -11]])
print(v)
print(a)

[[-2]
 [ 0]
 [ 1]]
[[  5   8  16]
 [  4   1   8]
 [ -4  -4 -11]]


In [280]:
a.dot(v)

array([[ 6],
       [ 0],
       [-3]])

In [281]:
np.matmul(a, v)

array([[ 6],
       [ 0],
       [-3]])

In [286]:
eigenvals, eigenvects = np.linalg.eig(a)

In [284]:
print(eigenvals)
print(eigenvects)

[ 1.+0.00000000e+00j -3.+2.71947991e-15j -3.-2.71947991e-15j]
[[ 0.81649658+0.j          0.14036888-0.55580947j  0.14036888+0.55580947j]
 [ 0.40824829+0.j         -0.71521317+0.j         -0.71521317-0.j        ]
 [-0.40824829+0.j          0.28742215+0.27790473j  0.28742215-0.27790473j]]


In [ ]:
import numpy as np
a = np.array([[3,1], [0,2]])  # establish a
a.dot(np.array([1,0]))  # check v1
array([3, 0])  # looks like 3 times v1, so v1 is in
a.dot(np.array([np.sqrt(3)/2, 0.5]))  # check v2
array([3.09807621, 1.        ])  # ok, so 1 is clearly twice 0.5, so is 3.098 twice sqrt(3)/2?
np.sqrt(3)
1.7320508075688772  # guess not! v2 is out
a.dot(np.array([-np.sqrt(2)/2, np.sqrt(2)/2]))  # check v3
array([-1.41421356,  1.41421356])  # still symmetric values where the first one is negative, so there exists some scalar for this vector that works as lambda, so this is an eigenvector; v3 is in
#  So, v1 and v3 are in, v2 is out.